### ISSUE TITLE
upsertCustomCC.js feedback V1

### ISSUE THREAD

**Issue by hnyende** [OpenFn/women-for-women#51]
## Describe the bug
A clear and concise description of what the bug is.See original issue #42 for the background. See [mapping sheet](https://docs.google.com/spreadsheets/d/1Bb8qLopGbrpPs_d1es71YH-uQDFZKi9594T4WRjiPP0/edit#gid=268449680) - Custom CC V1 for mappings.

METHOD_NOT_ALLOWED: HTTP Method 'PATCH' not allowed. Allowed are GET,HEAD,POST

## To Reproduce
1. Here is a link to a failed run on OpenFn.org wihch is indicative of the bug: https://www.openfn.org/projects/pdv34m/runs/rmk38nkg

### expression.js
Link to the job itself in Github: https://github.com/OpenFn/women-for-women/blob/master/jobs/committed/upsertCustomCC.js

## Expected behavior
For every 1 custom CC field in the CSV, 1 Opportunity will be upserted in SF, matching on Credit_Card_ID__c.

## To test/resolve
1. After the desired output is working locally (from the CLI), please [push commits to master || open a pull request].
2. [Please test the change on OpenFn.org by re-running this run (https://www.openfn.org/projects/pdv34m/runs/rmk38nkg) and confirming success.]

**Comment by aleksa-krolls** [comment]
@hnyende Mamadou will have space this morning, so I'm going to go ahead and move these to the backlog. 

@lakhassane Looks like we're getting this error because the datavalue is undefined. But I think this job needs work... it doesn't look setup to handle the `_json` array. See this state: https://www.openfn.org/projects/pdv34m/messages/ma9rmz7v

**Comment by lakhassane** [comment]
@hnyende @aleksa-krolls quick one.
Does this job needs to do what it does for each object in the json array?
Because my thoughts were we need to (1) look into all the object at once, (2) find the matching one and (3) assign it to the salesforce field.

**Comment by hnyende** [comment]
@lakhassane  yes, it should be for each object in the json array

**Comment by aleksa-krolls** [comment]
@lakhassane Hmm, so... multiple rows in the CSV may have the same `CCID`. Each of these rows need to update a different field on this `CCID` record. 

We can either... for each CSV row, update the Opportunity every time. (But this means the same record might be updated some 4-5 times in 1 run... and Salesforce may not like if we try to do that.) 

So I wonder if we should rather find every CSV row that belongs to the same SF record (matching on `CCID`)... and then only upsert that SF record one time (rather than 4-5times). So this might involve grouping the different `_json` items by `CCID` before mapping and upserting. What do you think?

**Comment by lakhassane** [comment]
@aleksa-krolls I implemented the pattern we talked about by building a new json array from the metadata.
replicated also for `upsertCustomDD`.
@hnyende this is ready for testing

**Comment by hnyende** [comment]
@lakhassane , I am getting an error `MALFORMED_ID: Honoree Contact: id value of incorrect type: Ruby Anita Russell`. See message link: https://www.openfn.org/projects/pdv34m/runs/ryaw6b8d
 
Can we try this:
1. Search Contacts where Name = 'Ruby Anita Russell', and then return the id so that npsp__Honoree_Name__c: contactMatch.Id
