### ISSUE TITLE
Mail and Text Opt In fields in Donors not upserting in SF

### ISSUE THREAD

**Issue by hnyende** [OpenFn/women-for-women#63]
## Describe the bug
For all contacts in `donors.csv` with `Yes`  values in the fields of `Ok to mail` and `OK to text`, the corresponding checkboxes in the SF contacts for `Mail_Opt_in__c` and `Text_Opt_In__c` remain unchecked after upserting. Why are these fields not populating? 

## To Reproduce
1. Here is a link to  OpenFn.org: https://www.openfn.org/projects/pdv34m/runs/rx8pwgw7

### expression.js
Link to the job itself in Github: https://github.com/OpenFn/women-for-women/blob/master/jobs/committed/upsertDonors.js

### state
Use the `WfWI NEW Sandbox`

**Comment by lakhassane** [comment]
@hnyende I don't think this is a bug.
In the specs it was said:
1. We fetch by personRef
2. If we match, we do _something_
3. if we don't match (which is the case in each of the objects in the message for the run above), **we (A) check if CG is more recent than what's in SF**.
4. If yes to point A we upsert a bunch of field, otherwise we do (B) upsert only one field:  `Committed_Giving_ID__c`. 
<img width="801" alt="Screen Shot 2021-07-12 at 16 11 10" src="https://user-images.githubusercontent.com/8411231/125320988-c7326680-e32b-11eb-85be-f0c7cce4c9ba.png">

So if you look at the screen we are on the `else` part of our condition because the LastModifiedDate in SF is always more up-to-date than the `LastChangedDateTime` in the message
