### ISSUE TITLE
upsertTransactionCardsV2: Dynamically set Campaign Source Code

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/women-for-women#73]
## Request
Mapping changes for #68 

On L134 and L154, add the mapping `Campaign.Source_Code__c': 'X'` where `X` is `'UKSPCC'`if...
`x.Amount` is multiple of 22 (sponsorship). Otherwise return `'UKRG'`. 

## state
https://www.openfn.org/projects/pdv34m/messages/mk585994

## expression
https://github.com/OpenFn/women-for-women/blob/2501a4d833168756821c1de1af7db8dc78674bf3/jobs/committed/upsertTransactionCardsV2.js#L134

**Comment by aleksa-krolls** [comment]
@lakhassane I _think_ this is the latest mapping change needed to ensure the Opportunity mappings look good. 

@hnyende I think we can re-test credit data syncing when this is done.

**Comment by aleksa-krolls** [comment]
@lakhassane Since the latest change we're encountering `UNABLE_TO_LOCK_ROW` error when bulk upserting Opportunities. 
https://www.openfn.org/projects/pdv34m/runs/rzd5dmab

It _might_ be because of Salesforce-side automation triggered when we upsert Opps... but we didn't see this error before, so I'm wondering if you have any ideas what might be causing it?

**Comment by lakhassane** [comment]
@aleksa-krolls it's likely that we have 2 jobs trying to upsert the same record. Can it be those 2 because from the logs I see they manipulated the same `Committed_Giving_ID__c` and the error happens only when the start time is equal.

<img width="1118" alt="Screen Shot 2021-08-11 at 15 46 22" src="https://user-images.githubusercontent.com/8411231/129061128-cd1b9432-0eaa-43e5-841e-653e5d65314b.png">
