### ISSUE TITLE
upsertCustomCCV2: Weird mappings to nonexistent columns throwing errors? 

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/women-for-women#94]
## Describe the bug
Seeing this error for the first time: https://www.openfn.org/projects/pdv34m/runs/r89p4p73
`INVALID_FIELD: No such column '0' on sobject of type Opportunity`

Where are these mappings coming from?
`'0': '0',`
` n: 'p'`

This job is sometimes succeeding, so not sure what's up: https://www.openfn.org/projects/pdv34m/runs/ryarmr4j

## To Reproduce
Feel free to re-run on prod: https://www.openfn.org/projects/pdv34m/runs/r89p4p73

### expression.js
upsertCustomCCV2.js 

### state.json
https://www.openfn.org/projects/pdv34m/messages/m66qrzma
FOR THESE CUSTOM JOBS ONLY... you can run on `WfWI Partial Sandbox - Salesforce` (un: support@openfn.org.apiuser.training`. Prod jobs are currently linked here. 

All other testing should be done with the `openfn` sandbox.

**Comment by lakhassane** [comment]
@aleksa-krolls I made the correction and run locally (can't on prod because of queue). It was an issue with the dynamicFields we map on some conditions. Here is a correct mapping.

![Screen Shot 2021-09-24 at 10 48 15](https://user-images.githubusercontent.com/8411231/134662683-da18440e-fc68-46ec-a44b-da7c4aa837e4.png)
.
