### ISSUE TITLE
upsertDirectDebits.js: TypeError [ERR_INVALID_ARG_TYPE]

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/women-for-women#97]
## Describe the bug
Haven't seen this one before...
`TypeError [ERR_INVALID_ARG_TYPE]: The "request" argument must be of type string. Received type boolean (true)`

## To Reproduce
Feel free to re-run on prod: https://www.openfn.org/projects/pdv34m/runs/061520a7-36dc-7d78-9345-6d49e1857aad

### expression.js
upsertDirectDebits.js

### state.json
See LP for `WfWI OpenFn Salesforce Sandbox`
https://www.openfn.org/projects/pdv34m/messages/06141ee9-6000-7ebd-8f25-1b33777751bd

**Comment by elias-ba** [comment]
Hey @aleksa-krolls could you please add me [to this job](https://www.openfn.org/projects/pdv34m/runs/061520a7-36dc-7d78-9345-6d49e1857aad) ? I think I do not have the rights to access it currently.

**Comment by elias-ba** [comment]
Hey @aleksa-krolls it looks like there was an issue with the adaptor installation. Because I saw `unknown` as the adaptor version in the run log. I have verified that the job runs successfuly on version `v2.6.3` both locally and on production and at this point in time I am not able to replicate the bug. Would you please confirm that it looks good from your side and please close this issue. Thanks

**Comment by aleksa-krolls** [comment]
ok thanks @elias-ba , looks ok now
